#*******************************************************************************
# Copyright (C) 2021-2022 CERTH
# 
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
# 
# SPDX-License-Identifier: EPL-2.0
#*******************************************************************************

FROM sonarqube:latest

RUN wget https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/latest-snapshot/sonar-cxx-plugin-2.1.0.253.jar -P /opt/sonarqube/extensions/plugins/